### C - Create
POST http://localhost:8080/accounts
Content-Type: application/json
{
    "name":"Wanderlei",
    "document":"1"
}

### R - Read
GET http://localhost:8080/accounts
Content-Type: application/json

### U - Update
PUT http://localhost:8080/accounts/123
Content-Type: application/json
{
    "name":"Wanderlei Magri",
    "document":"1",
    "balance":"100"
}

# D - Delete
DELETE http://localhost:8080/accounts/1
Content-Type: application/json